# Navigation Links
main:
  - name: Research
    url: /research/
    weight: 10
  - name: Talks
    url: /events/
    weight: 20
  - name: Blog
    url: /blog/
    weight: 30
  - name: Projects
    url: /projects/
    weight: 40
  - name: Software
    url: /software/
    weight: 50
  - name: Experience
    url: /experience/
    weight: 60
